# To write the first Python program
print("Hello world")
print("sadagakgjggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg")
print(2+3)
print(2**3)
print("สวัสดี", end="")
print("ชาวไพธอน")
print("สวัสดี", end="+")
print("ชาวไพธอน")
print("NeeMinnie")
print("Python " * 3)
print(sum(range(1, 10)))
print("\t\tMinnie")
print("This is "+"Saturday")
print("Coffee", "Tea", "Milk")
